<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
        <AnalysisLevel>preview</AnalysisLevel>
        <ImplicitUsings>enable</ImplicitUsings>
        <TargetFramework>net10.0</TargetFramework>
        <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Blazouter.Server\Blazouter.Server.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="package.json" Visible="false" />
        <None Include="Tailwind.txt" Visible="false" />
        <None Include="postcss.config.mjs" Visible="false" />
        <None Include="tailwind.config.js" Visible="false" />
    </ItemGroup>

</Project>